service: products
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  profile: personalAccount
  region: us-east-1
  httpApi:
    cors: true

functions:
  products:
    handler: ./lambdas/products-list.productList
    events:
      - httpApi:
          method: get
          path: /products
  productDetails:
    handler: ./lambdas/product-details.productDetails
    events:
      - httpApi:
          method: get
          path: /products/{id}
